### PR TITLE
Changed background Image and Weather Icon based on Location

### PR DESCRIPTION
**Pull request by shehabadel**
Alongside @gibbonhug  we did the following:

- Implemented a function that returns an object contains the `url` of the background image, and the weather Icon. All of them are determined related to the current weather.
- Created two hooks to set the background image and weather Icon
- Installed `react-helmet` in order to update the `body` in the head tag using `style` tag
- Pulled Sanjay's changes, and fixed conflicts

There's  an issue that requires some attention
image

I guess we should give the map a background color like `white` or something, instead of being transparent.
In addition whenever I move my cursor away from the map it'll set the location to "" which will set the card to "Loading", and might do something like breaks or delays (you can check it out)

Please check it out @gibbonhug @awilkescom @sadiq-b @SanjaySinghRajpoot

### CODE REVIEW

**Comment by awilkescom** [comment]
@sadiq-b Hey Sadiq - could you please review this PR?

**Review by sadiq-b — APPROVED** [review]
Hi @shehabadel  and @gibbonhug 

Very good PR description and commit history.
The new changes work has intended.

**Comment by shehabadel** [comment]
Merged the latest branch and currently testing it.
Perhaps it needs simple enhancement since the forecast for the selected city is left-aligned, we can make it center aligned.
image

**Comment by sadiq-b** [comment]
Hi @shehabadel the Pr has conflicting files with the base kindly look into it.

**Comment by shehabadel** [comment]
Merged the other updates, but seems like after we press `get current location`, no results are shown if we hovered over the world map. So we need to check out what happened here
image

@awilkescom @sadiq-b @SanjaySinghRajpoot @elmar8287

**Pull request merged**
