### PR TITLE
Forecast for 7 days using own daily "widget"

### PR DESCRIPTION
**Pull request by elmar8287**
## Used another approach to the daily forecast

In this PR we create the one-day card template and make it dynamic for 7 days of visualization

- We used [16 days Forecast API]("https://openweathermap.org/forecast16") and made logic to use only data for a week (https://openweathermap.org/forecast16)

### CODE REVIEW

**Comment by awilkescom** [comment]
@elmar8287 @dw2761 hey - I'm not sure it's best practice to have a PR in a "paused" state - probably best to close the PR for now, and send a new one when complete. What do you think?

**Comment by elmar8287** [comment]
> @elmar8287 @dw2761 hey - I'm not sure it's best practice to have a PR in a "paused" state - probably best to close the PR for now, and send a new one when complete. What do you think?

@awilkescom totally agree. I am going to solve this issue 👍

**Comment by elmar8287** [comment]
> > @elmar8287 @dw2761 hey - I'm not sure it's best practice to have a PR in a "paused" state - probably best to close the PR for now, and send a new one when complete. What do you think?
> 
> @awilkescom totally agree. I am going to solve the conflicts and ask close the PR

**Comment by elmar8287** [comment]
Screen shot:

image

**Comment by somadisingh** [comment]
Hey @elmar8287 I think the conflict is maybe because you used yarn as your package manager instead of npm. What you could do in order to resolve this issue is:
- Manually resolve the conflicts in package.json
- Copy base branch's package-lock.json (in this case the head repo) and replace it with your existing one.
- Then run npm install in your terminal and that should do it.

Also, @awilkescom I don't have the view access to conflicts in index.html & App.js files, could you possibly give me the access so I can help @elmar8287 in solving the conflicts?

**Comment by awilkescom** [comment]
@somadisingh Hey - you should have the rights on this repo, do you perhaps need the rights on @elmar8287 's repo?

**Comment by somadisingh** [comment]
Together with @elmar8287 on a meeting to resolve the conflicts

**Comment by somadisingh** [comment]
## Update
The issue is with ForecastCard.js For some reason the data is not being fetched from the API. The mapping to the array data results in empty map which is in initial state.  @elmar8287 is currently working on the issue.

**Comment by somadisingh** [comment]
Hey @elmar8287 so could you resolve the conflicts before pushing this PR to main?

**Comment by elmar8287** [comment]
> Hey @elmar8287 so could you resolve the conflicts before pushing this PR to main?

@somadisingh yeah, I am working on it 💯

**Pull request merged**
