### PR TITLE
Geolocation detect

### PR DESCRIPTION
**Pull request by thucvy**
### This is to implement issue #3

Initially, the city displayed will be "New York". User can either input the desired city into the input box or select the option 'Use current location' to get weather for their current location.

What has been implemented so far:
1. Added a link for user to click 'Use Current Location'
image

2. Once the link is clicked, there will be a prompt for user to select either they want to "Allow" or "Block" permission to access their location
image

3. If user select "Block", an alert will be displayed saying that "User deny Geolocation" and the city remains as the previous city
image

4. If user select "Allow", the current location of user will be detected and sent to OpenWeather API to display its weather. Current city value in the input box will be changed to an empty string
image

5. User can input another city into the input box to see a different city, then can always click the link "Use Current Location" to see back weather for current location
image

### CODE REVIEW

**Comment by awilkescom** [comment]
@shehabadel hey could you please review this PR?

**Comment by shehabadel** [comment]
> @shehabadel hey could you please review this PR?
@awilkescom @thucvy 
The current PR may have conflicts with the base branch, I guess it doesn't contain Sanjay's and Sadiq's [merged PR](https://github.com/MLH-Fellowship/prep-project-22.JUL.PREP.3/pull/12).

**Comment by thucvy** [comment]
> > @shehabadel hey could you please review this PR?
> > @awilkescom @thucvy
> > The current PR may have conflicts with the base branch, I guess it doesn't contain Sanjay's and Sadiq's [merged PR](https://github.com/MLH-Fellowship/prep-project-22.JUL.PREP.3/pull/12).

I'll try to merge the conflict and push the commit. Will let you know when it's done

**Comment by shehabadel** [comment]
> I'll try to merge the conflict and push the commit. Will let you know when it's done

If you needed any help let me know @thucvy

**Comment by thucvy** [comment]
@shehabadel conflict has been solved. Please feel free to review and let me know if you have any questions

**Comment by shehabadel** [comment]
> @shehabadel conflict has been solved. Please feel free to review and let me know if you have any questions

Looking good to me now I believe
@awilkescom can you confirm, please?

**Comment by awilkescom** [comment]
@shehabadel @thucvy @ASLManasa   Yes sounds good - feel free to Merge the PR :)

**Comment by shehabadel** [comment]
@ASLManasa @thucvy @awilkescom Sorry for responding late, I think there are new conflicts because of the merged branch. My apologies for responding late again.

**Comment by awilkescom** [comment]
Great! Thanks all!

**Comment by thucvy** [comment]
> @ASLManasa @thucvy @awilkescom Sorry for responding late, I think there are new conflicts because of the merged branch. My apologies for responding late again.

Conflicts have now been resolved and I also adjusted a bit on the UI for the button to use current location. Previously, it was just a text for you to click on, now changing it to a button with hover effect.
image

**Pull request merged**
