### PR TITLE
Daily forecast section

### PR DESCRIPTION
**Pull request by elmar8287**
In this PR was done:

- Fixed the folder structure. Cleared the unused files
- Created an API key and implement it in the project
- Created the Forecast component
- Investigated the API documentation and set up the Daily Forecast feature
- Implemented mentioned feature into the Forecast component

### CODE REVIEW

**Comment by awilkescom** [comment]
@SanjaySinghRajpoot Hey Sanjay - Can you please review this PR and give feedback to @elmar8287 and @dw2761 ?

**Review by SanjaySinghRajpoot — APPROVED** [review]

**Comment by SanjaySinghRajpoot** [comment]
The changes from this branch were merged with the main branch. In this commit https://github.com/MLH-Fellowship/prep-project-22.JUL.PREP.3/commit/fcd33b46a29c073fd4e7049457d57e1e493b3300

**Comment by awilkescom** [comment]
@elmar8287 @dw2761 @SanjaySinghRajpoot great sounds good - could someone make the final commit to this PR to resolve the conflicts?

**Review by SanjaySinghRajpoot — APPROVED** [review]

**Comment by SanjaySinghRajpoot** [comment]
Changes look good to me, I have already merged the changes for @elmar8287 in https://github.com/MLH-Fellowship/prep-project-22.JUL.PREP.3/commit/fcd33b46a29c073fd4e7049457d57e1e493b3300. Now the changes made by @dw2761 are to be merge from this PR.

**Comment by awilkescom** [comment]
@SanjaySinghRajpoot @elmar8287 @dw2761 Hey all! What's the status of this PR? As it's a bit behind, does it just need an update with the more recent PRs?

**Comment by elmar8287** [comment]
> @SanjaySinghRajpoot @elmar8287 @dw2761 Hey all! What's the status of this PR? As it's a bit behind, does it just need an update with the more recent PRs?

Hi @SanjaySinghRajpoot actually we continue with this issue in next PR https://github.com/MLH-Fellowship/prep-project-22.JUL.PREP.3/pull/20

**Comment by SanjaySinghRajpoot** [comment]
ok, @elmar8287 so do we need this PR or I can close this for now?

**Comment by elmar8287** [comment]
> ok, @elmar8287 so do we need this PR, or I can close this for now?

@SanjaySinghRajpoot We have to close it and go on with the new one. Thanks for your collaborations in this PR 👍 💯

**Comment by SanjaySinghRajpoot** [comment]
ok, closing this PR for now. Thanks everyone!!

**Pull request closed without merging**
