### PR TITLE
#10 use pod location

### PR DESCRIPTION
**Pull request by shehabadel**
Implemented  Issue #10 
```
Source a list of locations from Pod members, and allow the user to choose one of these locations to find out the weather.

For example, it could be a drop down menu with Cities.

Pod members can submit any location, it doesn't have to be personal!
```
Added a dropdown menu containing members' names and by selecting one from the dropdown, it fetches the weather of the pod's member's city.

### CODE REVIEW

**Comment by somadisingh** [comment]
Will have a look

**Comment by somadisingh** [comment]
@shehabadel could you increase the height of the input text too so that it matches the height of the drop down menu?

image

**Comment by somadisingh** [comment]
Also, since you have fed locations of 5 members as New Delhi, its highlighting the names. So just wanted to let you know if this is a bug maybe you could look into it.  

image

**Comment by shehabadel** [comment]
> @shehabadel could you increase the height of the input text too so that it matches the height of the drop down menu?
> 
> image

I will work on it now!

**Comment by somadisingh** [comment]
Another issue is, the activities aren't updating when the locations of any pod members are selected. What you could do to resolve this issue is `setActivities(response.data.choices[0].text);` paste this line whenever a pod member's location is selected

image

**Comment by somadisingh** [comment]
For some reason the input text is not showing up. Could you please look into this too.

**Comment by somadisingh** [comment]
For some reason the input text is not showing up. Could you please look into this too.

image


image

**Comment by somadisingh** [comment]
The abovementioned issues have been successfully resolved by @shehabadel . Will give a final check and merge the branch.

**Comment by shehabadel** [comment]
I don't get where did this came from, but I am adding `!important` to my padding though.
image

**Comment by shehabadel** [comment]
Finally it's okay. Please check it out @somadisingh

**Review by somadisingh — APPROVED** [review]
Everything in order. Weather & the activity cards are getting updated according when selecting the pod member's name from drop down menu. All parameters are getting updated accordingly. This branch is good to go @shehabadel

**Pull request merged**
