### PR TITLE
UI fixes, Glassmorphism, Updated README.md, Forecast Cards overlap on the 3D globe

### PR DESCRIPTION
**Pull request by somadisingh**
- Applied className to the forecast component.
- Used translucent background across all cards.

image

### CODE REVIEW

**Comment by somadisingh** [comment]
Updated README.md to include link to OPEN AI API

**Comment by somadisingh** [comment]
Fixed conflicts with the main branch

**Comment by somadisingh** [comment]
@thucvy maybe you could work on this with me

**Comment by somadisingh** [comment]
## Update
Fixed forecast cards overlap on the globe:

**THEN**

image


**NOW**

image

**Comment by shehabadel** [comment]
Great job @somadisingh everything looks great here!

**Pull request merged**
