### PR TITLE
Implemented weather based activity suggestions using OpenAI API

### PR DESCRIPTION
**Pull request by somadisingh**
# Feature Update: 
- App now uses GPT-3 AI API to suggest weather based activities.
- Kindly add the REACT_APP environment variable with the Open AI API key
- Fixed async error in component rendering 
- API now gives 5 activity suggestions based on the location and the current weather

### CODE REVIEW

**Comment by somadisingh** [comment]
# TODO
- Style the Activities card
- Make the card mobile responsive

**Comment by somadisingh** [comment]
## Attaching screenshots of the recommendations by the GPT-3 Bot:

New York
image

Paris
image

Rio De Janeiro
image

Wellington
image

Taipei
image

Pondicherry
image

**Review by dw2761 — COMMENTED** [review]
Looks good overall.

**Comment by somadisingh** [comment]
- NPM package `openai-api` has been used to fetch the ai engine for sending and receiving the prompt
- Variables `Configuration` & `OpenAIApi` have been created to fetch the api key from `.env` file and create a new configuration containing model stats.
- `openai.createCompletion` method has been used to send prompt to the AI engine. 
- Prompt: `Top 5 activities to do in ${city} when its ${result.weather[0].main}:`
- .then(response) method used to wait for the function to complete and then fetch the answers in a state variable.
- `activities` & `setActivities` state variables have been used to fetch and store the answer from the endpoint at `.JSON` file generated.

**Pull request merged**
