### PR TITLE
Add Air Quality Index (AQI) and description to indicate pollution level

### PR DESCRIPTION
**Pull request by thucvy**
This PR is to add the feature to indicate Air Quality Index (AQI) level and description as well as health recommendations to users based on air quality. There're different levels of air quality which was described in Issue #39 . All these levels are integrated accordingly to the app.

### Examples:
1. Currently in **New York**, air quality index is = **13** --> Air Quality is **Good** (level 1)
image

2. Currently in **Toronto**, air quality index is = **61** --> Air Quality is **Moderate** (level 2)
image

### What has been done:
1. npm package [react-circular-progressbar](https://www.npmjs.com/package/react-circular-progressbar) has been installed to show the AQI (`airQualityIndex`)
2. state variables for `airQualityIndex`, `airQualityValue`, `airQualityDesc`, `barColor` were created to show AQI value, AQI description, health recommendations, and set color for the circular bar accordingly
3. fetch API to get AQI value every time page rendered and either input value or longitude or latitude is change
4. create and add the `AQIPollution` component to add to the results box
5. adjust some styling for the result box and the AQI display part

### CODE REVIEW

**Comment by himanshu-thakur-7** [comment]
@thucvy The intended Air Quality feature is not visible in the deployment preview . Can you please look into this ?

**Comment by thucvy** [comment]
> @thucvy The intended Air Quality feature is not visible in the deployment preview . Can you please look into this ? Screenshot from 2022-07-27 12-10-59

nice catch! Thank you for reviewing this. I have just fixed the URL for my API link from http to https. Feel free to review again and let me know if there's any other issue. Thanks!

**Comment by himanshu-thakur-7** [comment]
Is the Air Quality Index available only at city level and not the  country level ( which seems understandable) but when i select countries with globe or map... the air quality index does not change (It either shows the default one with New York as city.. or the previously entered city) .. which ideally in my opinion if we are not showing at country level , AQI should not be visible in first place rather than showing wrong info.. what are your thoughts?
Screenshot from 2022-07-27 12-38-18
Screenshot from 2022-07-27 12-38-04
Screenshot from 2022-07-27 12-37-50

**Comment by thucvy** [comment]
> 

nice catch again. Actually, the AQI data is fetched using latitude and longitude so as long as latitude or longitude is changed, the AQI data should be changed. The reason why it was not changed when you clicked on the globe was because I initially set a condition to fetch AQI data only when _city and country exists together_ or _when user is using current location_. But now looking back again with the issue you mentioned, I don't think the condition matters anymore. 

Have also adjusted a few things on where I get the AQI data from API key so that the data appear to be more correct.

Please check again and let me know if there's any other issue.

Thank you!!

**Comment by thucvy** [comment]
> Is the Air Quality Index available only at city level and not the country level ( which seems understandable) but when i select countries with globe or map... the air quality index does not change (It either shows the default one with New York as city.. or the previously entered city) .. which ideally in my opinion if we are not showing at country level , AQI should not be visible in first place rather than showing wrong info.. what are your thoughts? Screenshot from 2022-07-27 12-38-18 Screenshot from 2022-07-27 12-38-04 Screenshot from 2022-07-27 12-37-50

nice catch again. Actually, the AQI data is fetched using latitude and longitude so as long as latitude or longitude is changed, the AQI data should be changed. The reason why it was not changed when you clicked on the globe was because I initially set a condition to fetch AQI data only when city and country exists together or when user is using current location. But now looking back again with the issue you mentioned, I don't think the condition matters anymore.

Have also adjusted a few things on where I get the AQI data from API key so that the data appear to be more correct.

Please check again and let me know if there's any other issue.

Thank you!!

**Comment by himanshu-thakur-7** [comment]
looks good to me now . Great Work @thucvy !! Merging now.

**Comment by thucvy** [comment]
> looks good to me now . Great Work @thucvy !! Merging now.

awesome! Thank you for the support!

**Pull request merged**
