### PR TITLE
Made the website responsive

### PR DESCRIPTION
**Pull request by somadisingh**
Fixed the responsiveness of all components on the webpage. Tested across the following breakpoints:

- 320px  - 480px -> Mobile devices
- 481px  -768px -> iPads, Tablets
- 769px  - 1024px -> Small screens, Old laptops
- 1025px -1200px ->Desktops & New Laptops
- 1201px  - 1600px  ->  Large screens, TV

### CODE REVIEW

**Comment by somadisingh** [comment]
## Improved responsiveness for mobile phones:
- Increased font size (h1, h2, h3 & p)
- Made the widget scrollable
- Now the suggestion cards are aligned in a single file

**Comment by awilkescom** [comment]
@thucvy could you please review and merge this PR?

**Comment by somadisingh** [comment]
Tweaked the location button's responsiveness for extra small & extra large screens.

**Comment by thucvy** [comment]
@somadisingh @codewarsfx I reviewed and everything looks good except for the 1 issue on the button width that make it a bit too small on the ipad/tablets screen, hence the overflow of the text inside the button --> @somadisingh has already solved this issue in commit #5117707

Currently, there're some conflicts and @somadisingh is trying to solve. I'll collaborate with @somadisingh on this.

Once everything is sorted out, will review once again and merge this PR

**Comment by somadisingh** [comment]
Resolved App.js conflicts, missing initializer for const. Fixed the global weather map overflow. Changed input box and location button width for extra narrow and extra wide screens. Fixed the test input overflow for iPad & Tablets. @thucvy could you please review it once more before merging it. Thanks!

**Comment by thucvy** [comment]
everything works perfect now and code is looking good. Approved and merging the PR now!

**Pull request merged**
