### PR TITLE
Get the right object according to the weather #4

### PR DESCRIPTION
**Pull request by saswatsam786**
This **PR** is made in response to issue #4 .

### Changes Made:
1) Card designs for the objects were made.
2) Functionality was added to show the required cards with respect to the weather.

### After Change Picture:
Screenshot 2022-07-21 at 1 10 23 AM

Screenshot 2022-07-21 at 1 12 22 AM

**@saswatsam786** and **@indywip** made this **PR**.

Any suggestion will be appreciated.

### CODE REVIEW

**Review by elmar8287 — APPROVED** [review]
Hi, @saswatsam786.

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

### Highlights

- Very informative PR description 👍 
- Nice implementation of current milestone features 🥇 
- Good UI 👍 
- Nice commits history 💯 

### Optional suggestions

- Please, consider in the future writing the commits with a Capital letter, to make your commits history look more professional 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
If you think that the code review was not fair, you can request a second opinion

**Comment by awilkescom** [comment]
@elmar8287 @saswatsam786 @indywip   Looks great - can you do a final PR to resolve the conflicts for App.js? And what do we think about the other conflicts?

**Comment by saswatsam786** [comment]
@awilkescom I have resolved all the merge conflicts. I have solved the conflict with APP.JS and with all the lock and JSON files too. If you are satisfied with the pr, then please merge it.

**Comment by awilkescom** [comment]
Awesome - Giving it a merge

**Pull request merged**
