### PR TITLE
Add a toggle to switch between Celcius/Fahrenheit

### PR DESCRIPTION
**Pull request by gibbonhug**
This PR addresses [Issue #8](https://github.com/MLH-Fellowship/prep-project-22.JUL.PREP.3/issues/8). 

pr

I created state for the current unit system (metric(C) or imperial(F)). Changing the state with the toggle does not affect the unit in the API request (which is always in metric/Celcius), because I did not want to make calls each time a user used the toggle. Switching from C to F just performs the C to F conversion equation on the existing temperature data.

The temperature data that the API fetches in Celcius is retrieved with 2 decimal places. To display it with 2 decimals in Fahrenheit, I created a utility function to truncate decimals, which I added to the existing Utilities folder.

The toggle (UnitToggle) itself is its own component, with a folder for its JS and its styling, to follow the existing folder structure. When clicked, the toggle switches between two [MLH brand colors](https://mlh.io/brand-guidelines) I set as CSS variables. 

I had difficulties integrating this with the forecast widget in [https://github.com/MLH-Fellowship/prep-project-22.JUL.PREP.3/issues/1](https://github.com/MLH-Fellowship/prep-project-22.JUL.PREP.3/issues/1). I tried passing the current unit down as a prop but could not do this. @dw2761  gave me the go-ahead to make this PR without the widget integration.

### CODE REVIEW

**Comment by gibbonhug** [comment]
There are a lot of changes shown because of my Prettier extension, sorry about that.

**Review by dw2761 — COMMENTED** [review]
Hi Julian, since I also worked on this issue, and I wanted to integrate this toggle into the forecast card like this:
image

do you mind me changing your code and delete that toggle button and integrate that into the forecast board?

**Comment by gibbonhug** [comment]
That works :)

**Comment by somadisingh** [comment]
@gibbonhug this issue was implemented by @dw2761 in her PR merge, so I will be closing it, but feel free to open it if you need to. 

**Celsius Toggle**

image


**Fahrenheit Toggle**

image

**Pull request closed without merging**
